language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t frontent/docker_k8s -f Dockerfile.dev .

script:
  - docker run -e CI=true frontent/docker_k8s npm run test -- --coverage
